/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/footer/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/header/AppHeader.vue')['default']
    AppModal: typeof import('./src/components/modal/AppModal.vue')['default']
    AuthDropdown: typeof import('./src/components/layout/header/desktop/dropdown/AuthDropdown.vue')['default']
    CameraFeed: typeof import('./src/components/video/CameraFeed.vue')['default']
    Checkbox: typeof import('./src/components/form/Checkbox.vue')['default']
    DarkToggle: typeof import('./src/components/layout/header/darkToggle/DarkToggle.vue')['default']
    DesktopNav: typeof import('./src/components/layout/header/desktop/DesktopNav.vue')['default']
    DesktopNavItems: typeof import('./src/components/layout/header/desktop/nav-items/DesktopNavItems.vue')['default']
    DesktopNavItemsAuth: typeof import('./src/components/layout/header/desktop/nav-items/DesktopNavItemsAuth.vue')['default']
    Dropdown: typeof import('./src/components/form/Dropdown.vue')['default']
    EmailInput: typeof import('./src/components/form/EmailInput.vue')['default']
    FooterInfo: typeof import('./src/components/layout/footer/info/FooterInfo.vue')['default']
    FooterNav: typeof import('./src/components/layout/footer/nav/FooterNav.vue')['default']
    HeaderNav: typeof import('./src/components/layout/header/HeaderNav.vue')['default']
    HomeAuth: typeof import('./src/components/home/HomeAuth.vue')['default']
    HomePublic: typeof import('./src/components/home/HomePublic.vue')['default']
    HorizontalLogo: typeof import('./src/components/logo/HorizontalLogo.vue')['default']
    LoginForm: typeof import('./src/components/auth/login/LoginForm.vue')['default']
    MenuCloseIcon: typeof import('./src/components/icons/MenuCloseIcon.vue')['default']
    MenuOpenIcon: typeof import('./src/components/icons/MenuOpenIcon.vue')['default']
    MobileHeader: typeof import('./src/components/layout/header/mobile/MobileHeader.vue')['default']
    MobileNav: typeof import('./src/components/layout/header/mobile/MobileNav.vue')['default']
    MobileNavDrawer: typeof import('./src/components/layout/header/mobile/nav-items/MobileNavDrawer.vue')['default']
    MobileNavItems: typeof import('./src/components/layout/header/mobile/nav-items/MobileNavItems.vue')['default']
    MobileNavItemsAuth: typeof import('./src/components/layout/header/mobile/nav-items/MobileNavItemsAuth.vue')['default']
    MobileNavOverlay: typeof import('./src/components/layout/header/mobile/MobileNavOverlay.vue')['default']
    ModalCloseIcon: typeof import('./src/components/icons/ModalCloseIcon.vue')['default']
    ModalFooter: typeof import('./src/components/modal/ModalFooter.vue')['default']
    ModalHeader: typeof import('./src/components/modal/ModalHeader.vue')['default']
    MoonIcon: typeof import('./src/components/icons/MoonIcon.vue')['default']
    NumberInput: typeof import('./src/components/form/NumberInput.vue')['default']
    PasswordInput: typeof import('./src/components/form/PasswordInput.vue')['default']
    PasswordResetForm: typeof import('./src/components/auth/password-reset/PasswordResetForm.vue')['default']
    Playground: typeof import('./src/components/form/Playground.vue')['default']
    Radio: typeof import('./src/components/form/Radio.vue')['default']
    RegisterForm: typeof import('./src/components/auth/register/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignOutIcon: typeof import('./src/components/icons/SignOutIcon.vue')['default']
    SunIcon: typeof import('./src/components/icons/SunIcon.vue')['default']
    TextArea: typeof import('./src/components/form/TextArea.vue')['default']
    TextInput: typeof import('./src/components/form/TextInput.vue')['default']
  }
}
